
import { Link } from "react-router-dom";

const About = () => {
  return (
    <div>
      <h1>ABOUT</h1>
      <Link to="/">Home</Link>
      <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione, officia. Et doloribus sunt adipisci vero quo nihil illum architecto commodi voluptates dolorem vel quas ipsum eius consequuntur animi, minus ratione.
      Officiis harum est quidem odit. Consectetur qui voluptas error porro cumque magnam libero nesciunt! Nam eaque voluptates aut amet repellendus, ullam pariatur officia fugiat! Eligendi odio dolorem ad tempora dolor?
      Maiores alias asperiores sit architecto quisquam accusamus excepturi temporibus pariatur magni nemo necessitatibus, reiciendis quidem repudiandae rerum vitae aliquid quaerat deleniti fugiat esse aliquam. Porro commodi dolor necessitatibus quod ullam.
      Excepturi magnam rem expedita nihil? Inventore amet assumenda quos voluptatem quod porro repellat, quasi fugit soluta fugiat mollitia, libero voluptas exercitationem eum accusantium atque. Suscipit eius provident consectetur nihil laboriosam!
      Enim laborum repellendus sunt nam rem saepe voluptate sit facilis impedit expedita, porro minus quos ab similique voluptatum numquam earum neque perferendis. Aperiam eligendi doloribus culpa optio cupiditate velit expedita?
      Molestiae earum voluptates ut soluta commodi officia odio, cupiditate voluptatum dignissimos velit est magnam. Sapiente sint mollitia distinctio obcaecati? Cupiditate atque molestias eligendi, voluptate ipsum aperiam officiis doloremque blanditiis et!
      Neque soluta tempora harum delectus corrupti dicta expedita officia quo repudiandae, voluptatum non quod natus corporis animi excepturi, sint in, quae dignissimos consequatur iusto facere minima ad! Vero, rerum culpa.
      Minus laborum, optio amet commodi saepe tempore cum natus provident cupiditate nihil delectus eius vero, nemo deserunt, aut est. Cupiditate placeat modi earum magni fugiat aspernatur commodi ullam iusto quidem.
      Facilis est quos cumque natus sequi porro, necessitatibus voluptatem sapiente consequatur cum? Voluptatibus aut, vero, porro recusandae debitis ratione voluptate officiis obcaecati vel iure modi repudiandae quaerat delectus doloremque eos!
      Possimus magnam nesciunt voluptatum saepe incidunt in voluptas atque nostrum earum. Illo modi quasi quas soluta, ducimus commodi cumque aperiam consequatur molestiae ex delectus hic tenetur doloremque. Atque, reprehenderit enim.
      Natus neque necessitatibus harum? Ab eveniet asperiores consequatur, culpa corporis voluptatum. Nemo, asperiores eveniet aliquam impedit distinctio ex quisquam ad molestias in recusandae obcaecati odit. Error soluta deleniti voluptate veritatis!
      Deserunt minus nisi blanditiis quisquam mollitia delectus odio reprehenderit eum consequatur a ipsa et minima, at nobis quae quidem sunt labore repellat natus magnam animi aut modi debitis provident? Ab?
      Labore deleniti aliquam ea possimus omnis temporibus vero repudiandae eligendi quas assumenda libero ratione voluptatibus veniam commodi, in alias totam aut. Accusantium ipsam voluptatibus dolores repudiandae quos vitae pariatur id.
      Laborum porro doloribus a iste suscipit alias tempora beatae itaque laudantium eum rem nemo culpa ullam sunt cum voluptatibus quidem officia accusamus, molestiae placeat. Est aut minima pariatur quis. Architecto.
      Nesciunt inventore, maiores quos iusto laudantium dolore minus magnam id debitis, in assumenda repudiandae quidem delectus vitae ratione recusandae voluptas dolor illo. Dolorem ratione id repellendus molestiae cumque rem recusandae!
      Dolor quidem sapiente molestias alias perspiciatis magni itaque aperiam ipsa. Architecto sit rerum voluptas sed perferendis magnam magni non necessitatibus commodi quisquam doloribus soluta quasi odio, aspernatur excepturi repellat ab.
      Tenetur, molestias minima. Obcaecati expedita qui consectetur magni! Optio rem dolorum natus debitis ipsam tenetur illo sapiente, vero fugiat, dignissimos veniam incidunt nam sed numquam laborum minus explicabo soluta. Error?
      Nam accusamus temporibus error maxime nesciunt, autem assumenda illo in similique unde necessitatibus quisquam, maiores soluta, consectetur consequatur. Explicabo, eos. Nostrum excepturi labore perspiciatis possimus ipsam ipsum atque nemo quae?
      Quasi atque ipsam repellat maxime voluptates eaque ratione distinctio. Reprehenderit velit, sequi laboriosam necessitatibus dignissimos voluptatum adipisci modi quas hic soluta similique ullam non possimus ex dolorum est maxime? Sapiente.
      Neque ab doloribus aut. Debitis aliquam magni et nihil reprehenderit impedit adipisci eligendi exercitationem, sint ipsum excepturi officia iure illum quae soluta id nostrum quos maiores, blanditiis itaque delectus? Harum?
      Molestias unde harum quis quod, perferendis numquam ab consequatur doloribus laudantium ea, fuga, veritatis nam nulla iste nihil impedit odit. Praesentium molestias culpa ut voluptatem eos numquam commodi, optio enim.
      Error veritatis voluptate est blanditiis? Quidem veniam eligendi numquam neque iure incidunt fuga nulla laboriosam perspiciatis voluptatum non suscipit mollitia, molestiae, laudantium quos exercitationem atque necessitatibus sapiente minus dolor fugit.
      Porro incidunt fuga adipisci reprehenderit, placeat veniam commodi reiciendis quibusdam iure impedit odit! Fugiat voluptates, nihil autem blanditiis architecto temporibus ab repudiandae aliquam tempora. Laudantium magni a incidunt ea aperiam?
      Officia ratione minima ipsam reiciendis adipisci! Cupiditate, earum veniam accusamus blanditiis, ad illo illum provident maxime recusandae numquam fugiat sequi labore quae, amet excepturi voluptas non est perspiciatis dolorum incidunt.
      Accusamus quos nam tempore quis voluptatibus esse consequuntur et corrupti, rerum sapiente tenetur? Maiores quaerat accusamus amet corrupti quae obcaecati saepe nihil odit, pariatur ad sunt. Velit perspiciatis enim et.
      Obcaecati, in optio excepturi soluta debitis mollitia cum voluptatibus enim. Impedit corporis saepe provident officiis sequi alias vero maiores ipsum nostrum, sapiente doloribus nihil modi soluta, molestiae placeat eveniet repellat.
      Illum quia architecto quos quidem aliquid, pariatur deleniti rem reprehenderit praesentium cumque adipisci soluta aliquam. Quis delectus dolores est labore, et rerum laborum maxime, ducimus ipsa nesciunt molestiae magni iure?
      Eum officia at voluptate beatae nihil, soluta unde, eligendi a distinctio placeat tenetur adipisci repellendus porro fuga, reprehenderit ipsum dolores necessitatibus fugit quos nostrum atque delectus ratione dolorum! Facilis, optio?
      Eius assumenda sint est mollitia placeat fuga, voluptatum magni corrupti fugiat tempora nesciunt dolorem corporis consectetur numquam quidem labore modi, explicabo dolore iusto totam repudiandae natus itaque voluptas consequatur! Eveniet!
      Iste quisquam accusantium, debitis quidem atque odit distinctio labore minima illum itaque quibusdam soluta consectetur optio assumenda commodi cum laudantium eaque aut non illo sunt ea voluptatem! Molestias, tenetur placeat.
      Et illum eveniet eaque similique id, mollitia libero odio. Nesciunt eos temporibus distinctio aliquid explicabo sapiente quidem sequi animi soluta enim incidunt, inventore et excepturi quis! Perferendis eos modi quas.
      At qui error excepturi minus magni exercitationem, sit perspiciatis veritatis. Architecto animi debitis, velit beatae, quas accusamus id laboriosam alias eligendi iure, voluptas natus perspiciatis corporis doloribus hic? Nostrum, temporibus!
      Quam, quasi! Quia architecto aspernatur, maiores tempora ullam ex facilis sint, quisquam unde mollitia officia suscipit totam nam doloribus quibusdam quas veniam, commodi quae vero. Cumque officia vitae recusandae doloribus.
      Quis harum voluptatibus sint id consequatur hic ex obcaecati suscipit. Ipsam id incidunt officia corrupti velit? Minima, aliquid repellendus? Et nobis necessitatibus ad laborum dolor qui, dolorem at blanditiis vel!
      Quis velit porro facere animi omnis, consectetur illum ab! Placeat neque eum qui dicta quas quos tempore debitis, recusandae culpa fuga velit officia distinctio vero minima aut porro. Cupiditate, debitis?
      Ut magni illo soluta dolorum perspiciatis dicta. Enim nostrum quos atque incidunt, doloribus deleniti repellat asperiores placeat fugiat nemo porro libero illo consequuntur ipsa, officia inventore animi quod, maiores sunt.
      Blanditiis quos error rem exercitationem ab est explicabo. Vero ipsum hic, totam, doloremque dolorem tenetur excepturi quos, deserunt praesentium itaque temporibus consectetur rerum est ratione ad? Laborum sequi minus dignissimos.
      Placeat quia, recusandae voluptate fuga corrupti possimus? Eaque voluptates cumque dolorem veniam, eius non esse recusandae laborum eum amet quisquam enim dolor consequatur ab rerum similique. Omnis recusandae eos sit!
      Id magni voluptates repellat veniam dolores porro a nostrum ipsum architecto illo, neque, autem ipsam expedita fugiat inventore amet harum nam officia optio atque aliquam. Ab commodi totam deleniti cum.
      Necessitatibus, delectus fugiat! Iure id in quidem deleniti cumque aliquam libero aspernatur. Doloremque, non maxime, autem distinctio, sint repellat illo hic sed eum quae ipsum. Fugit autem aliquam officiis molestias!
      Minima nam quia reprehenderit amet inventore distinctio ullam voluptatum. Magnam, ratione, omnis eveniet obcaecati aliquid delectus ipsum temporibus adipisci ipsa harum, quasi molestiae similique est quis cumque corporis ducimus suscipit.
      Harum soluta quasi eveniet praesentium deserunt esse quod quae sed accusamus impedit sint dignissimos nostrum itaque fugit placeat adipisci consectetur, eius sit optio asperiores architecto molestias pariatur error? Adipisci, sit.
      Vero, ratione? Odio quos provident eligendi voluptatibus nesciunt, aliquam fugit culpa laudantium facere repellendus vel eum quasi a deserunt earum, quas doloribus perspiciatis quaerat ut maxime ab, atque iure molestiae!
      Voluptate accusantium voluptatum quas magnam. In animi quos eius ab quas quod possimus error dolore temporibus praesentium magnam, sunt assumenda, veritatis mollitia tempore labore vero libero totam nisi omnis fugiat?
      Dolore suscipit, aspernatur distinctio dignissimos commodi, tempora assumenda officia laudantium repellendus veniam quasi, obcaecati libero quod unde voluptatibus sint est inventore aut? Provident ratione, dolores vel fugiat magni nam eaque.
      Consectetur earum fuga reiciendis optio eius eaque sequi, ex vero quis harum voluptate dolores aut iusto aperiam ullam vel magni porro pariatur quod cupiditate adipisci. Officia expedita asperiores quo temporibus.
      Voluptate, laborum odit nostrum corrupti iste dolores aspernatur velit in ad quis assumenda! Et dignissimos asperiores aperiam impedit vel sunt vero. Tempora hic eaque nisi reprehenderit, labore nulla ipsa quidem!
      Unde deleniti perferendis at illo eius ab quam rerum exercitationem. Aperiam, cupiditate! Suscipit earum quia nobis expedita officiis nesciunt corporis, unde architecto adipisci culpa neque consequatur tempora laborum rem delectus.
      Quos nostrum omnis dolorum possimus quam, accusamus delectus voluptatum error eum tenetur quidem quas ullam natus ea consequatur! Numquam totam perferendis laborum hic reprehenderit quae aperiam excepturi ratione cupiditate expedita.
      Nemo sapiente alias voluptate doloribus sequi maiores dolores, ullam quas repellendus quia laborum ut esse ex at enim ipsa! Fugit aut quo officia velit inventore temporibus dolorem ea recusandae eveniet.
      Deserunt accusamus, aliquid deleniti sed ipsa veniam numquam eum ipsam obcaecati possimus harum ab, molestiae commodi ex dolorem molestias itaque dolorum expedita id soluta? Non doloremque aliquid nihil eum voluptates.
      Laborum nesciunt deserunt adipisci cupiditate laboriosam quidem omnis aspernatur suscipit laudantium saepe nulla iusto perspiciatis quo sit aut, blanditiis iste! Possimus vel sed at nobis doloribus error aspernatur culpa alias!
      Porro quae illum quia animi optio expedita saepe necessitatibus repudiandae placeat. Numquam voluptatum, corporis, at sunt inventore unde, blanditiis nemo adipisci veritatis molestias animi nostrum rerum saepe? Quam, iusto beatae.
      Eos fugit tenetur veniam voluptatum vitae tempora officia, nam ea nulla non minus, obcaecati, pariatur facilis iusto veritatis perspiciatis. Est ex unde nobis, eos debitis consequuntur! Quidem pariatur exercitationem provident.
      Porro debitis incidunt minus ducimus inventore. Dolorem dolorum delectus nam labore officia unde obcaecati ut in natus, doloremque tenetur accusantium voluptatum. Aspernatur cum alias dolor, quos excepturi voluptatibus qui ullam.
      Dolore quisquam dignissimos non. Nisi natus eos in velit enim! Exercitationem harum fuga reprehenderit quisquam expedita natus, reiciendis officiis rem voluptatibus sint, magni quis cum modi incidunt quo eaque dolorum.
      Ullam, incidunt facilis! Suscipit earum cum voluptate nemo cumque, hic beatae eum non nesciunt, illo laborum. Quod sit esse, sequi sed laborum illo explicabo animi eum. Sit reiciendis tempora nesciunt.
      At aut earum, facere voluptatibus tempore deleniti. Tenetur earum nemo consectetur nesciunt beatae dolorum fugit voluptas blanditiis consequuntur vitae, quo nam quidem vero quis accusamus excepturi porro iste, eius dolor.
      Cumque perspiciatis exercitationem voluptatum, aut inventore natus vel consectetur est, temporibus non iusto cum rem ut corporis nostrum! Exercitationem error ullam quidem in saepe natus nobis vero earum eius ex.
      Repellendus, nihil labore voluptatum iusto consequatur id temporibus odio, earum tenetur minus dolores deleniti ab recusandae obcaecati assumenda veritatis odit ratione cupiditate. Maxime corporis dolorem, praesentium ducimus tenetur quaerat voluptatibus.
      Inventore quibusdam unde similique dolores voluptates rem adipisci ad nemo est ratione repellat, dicta veritatis repellendus, doloribus tenetur qui, maxime voluptas totam placeat dolorem? Cum sunt recusandae et reiciendis exercitationem!
      Totam quis vitae unde voluptas? Praesentium iure perspiciatis temporibus, autem cum sapiente at tenetur sequi aliquam omnis laborum fuga iusto. Ex ipsam quos dignissimos nihil distinctio libero eum quo quis?
      Reiciendis facere harum delectus, omnis aliquam similique pariatur temporibus at nemo excepturi ducimus minima voluptatem veniam qui id vero quo, quos cupiditate, illo autem ea atque corrupti. Nisi, quaerat minus.
      Dolores quasi maxime reiciendis atque minima voluptas natus autem mollitia, rerum ad beatae adipisci, neque iste, culpa accusantium. Minima mollitia corporis neque vel. Sunt dolore sit esse ipsum ullam non.
      Pariatur labore, magnam accusantium qui possimus sapiente deleniti reprehenderit explicabo, impedit quidem, consectetur harum eveniet nostrum cum et laudantium tenetur vero modi? Exercitationem eum earum, minus temporibus maxime adipisci distinctio!
      Perspiciatis accusamus animi molestias debitis maiores, aperiam soluta aliquid aspernatur unde obcaecati laborum consequuntur sint est quod autem earum et. Nesciunt odit fugiat illum facilis voluptates harum soluta necessitatibus veritatis!
      Accusantium est quo maiores, recusandae fuga eveniet sequi aspernatur! Porro minus molestiae perspiciatis ipsa rerum, cupiditate necessitatibus architecto delectus, eaque excepturi ullam enim blanditiis. Minima tempore aut sunt soluta doloremque.
      Quod possimus voluptas officiis est optio iste eveniet, odio minima rerum, praesentium officia nesciunt eligendi consequatur voluptatum assumenda. Sit, optio totam explicabo saepe ex vitae doloremque esse recusandae officiis suscipit.
      Exercitationem quo modi repellendus, temporibus officiis facilis sit culpa dignissimos minima eligendi cum sed esse obcaecati debitis ipsum autem architecto nihil commodi voluptate explicabo perferendis. Omnis delectus rerum possimus minima!
      Perferendis fuga quibusdam maiores omnis adipisci. Natus facere illo expedita nobis similique culpa odit id laborum consectetur labore dolores, doloremque nisi, excepturi amet aperiam porro. Aut ad eveniet voluptatibus nam.
      Accusamus beatae nihil nobis natus fugiat porro id eveniet ipsa perspiciatis! Pariatur cupiditate natus repellendus eaque nesciunt culpa iste dolor voluptas minus! Quasi, incidunt. At est repudiandae vitae fuga voluptates!
      Laborum accusantium quidem repellat amet voluptate? Nemo cum suscipit eveniet perferendis expedita nulla odio sequi, est dicta, deserunt voluptate exercitationem sed id modi nesciunt veritatis maxime. Optio iure ea aut.
      Sequi provident aperiam dolor illum natus, iure eligendi placeat aspernatur voluptate sit voluptatibus praesentium! Quibusdam magnam nulla, neque, reprehenderit vero doloremque et saepe excepturi, eius aliquam rerum sunt quam quasi.
      Repudiandae laudantium facere temporibus quam adipisci quisquam alias quaerat quis reprehenderit! Perferendis harum cumque eaque repellat dignissimos sint odio eum facilis molestiae blanditiis quod, consequatur amet aperiam veniam dolor dolore?
      Rem reprehenderit impedit, vel quam nostrum eum porro architecto doloribus assumenda debitis asperiores quo officiis quaerat, expedita consectetur sequi harum, ipsa possimus aspernatur. Molestiae veritatis ratione sapiente enim dolore quia.
      Delectus excepturi mollitia iure impedit doloremque voluptatibus, sit fugit ipsa distinctio eos blanditiis aspernatur ut ratione natus in. Eius excepturi molestias laudantium mollitia non voluptatem consequuntur cupiditate neque minima voluptates?
      Laudantium veniam dolorum sunt totam, eos inventore necessitatibus molestiae nihil labore sint harum doloremque obcaecati quasi atque consectetur corrupti error amet magnam suscipit quidem! Cumque temporibus atque obcaecati repudiandae totam!
      Aspernatur deleniti laboriosam corrupti quae, et atque repellendus, tempora itaque nihil unde earum voluptates saepe, maiores culpa rem reiciendis inventore? Harum minus minima ducimus voluptatum! Praesentium repellendus excepturi minima vitae.
      Numquam explicabo, voluptatem labore reiciendis mollitia vero quod non praesentium optio quisquam ab veniam et asperiores, culpa necessitatibus ut natus consequatur cum, eius doloribus earum voluptatum odio quam. Dolor, nihil.
      Assumenda voluptatum ipsa nam provident doloribus nostrum laboriosam veniam sit alias laborum aut non, possimus deserunt amet! Eum, aperiam! Facilis quis consequuntur nam delectus expedita natus quibusdam saepe quisquam! Quasi!
      Error blanditiis dolorum quasi repellendus in neque! In culpa consequuntur, nesciunt iure aliquid earum sunt, ea voluptate autem quas libero facere incidunt exercitationem molestias temporibus dolorem porro vitae rerum sapiente!
      Perferendis blanditiis minus necessitatibus iusto commodi totam neque, a magni modi obcaecati, accusantium sit natus quae! Expedita doloremque optio aspernatur porro numquam dolorem, est minima hic! Sit, reprehenderit eveniet. Exercitationem?
      Tempora dolore sunt unde? Dolore perspiciatis eos labore, obcaecati quia unde consequatur asperiores? Nam totam velit possimus aperiam! Minus, modi! At consectetur voluptates sed hic sequi molestiae nisi est quis.
      Velit harum officiis cupiditate ratione beatae pariatur libero minus dolore iusto, obcaecati odit eaque possimus odio. Nisi saepe quos fuga voluptatem vero, nemo accusamus asperiores animi, magnam consequuntur, cupiditate pariatur?
      Quibusdam, sint libero enim ut eos maiores dolor iure dolore. Cum, libero laboriosam voluptas eaque asperiores sequi? Sed, a. Neque facere tempore, quam repellendus iusto consectetur quibusdam culpa maiores ipsam.
      Voluptatem atque quos tempora maxime earum excepturi ipsum doloremque inventore ducimus? Corrupti recusandae laborum, reiciendis minus pariatur unde non tempora dignissimos amet incidunt quam at quae ab deleniti neque voluptatem.
      Reprehenderit, corrupti nemo, blanditiis amet minima soluta porro, provident voluptate dolores accusamus debitis minus voluptatum asperiores! Earum iusto debitis sint excepturi modi nesciunt laboriosam impedit quae. Fugit voluptate eveniet asperiores.
      Ipsam vero reprehenderit dignissimos culpa facilis nihil similique? Iste exercitationem quam quia reiciendis aperiam, nulla, consectetur eos officia cupiditate nam quasi harum temporibus eveniet eius odit, distinctio quod amet natus?
      Vitae dolore dolorem adipisci aspernatur magnam. Atque eligendi dicta, labore error eveniet laudantium, omnis laborum debitis esse maiores mollitia eum itaque corporis! Provident id possimus dolorem voluptatem, tempora exercitationem culpa!
      Corrupti esse exercitationem ab cumque distinctio praesentium voluptates sit repudiandae omnis, minus in unde sunt quia repellendus nihil voluptatibus, ducimus corporis ea inventore ullam ipsa labore. Alias aliquam sit rem?
      Repudiandae dolor autem esse numquam magni iusto commodi earum illum laudantium provident, delectus nobis soluta. Consectetur harum sint voluptates aliquam accusamus labore quaerat facilis, vel nemo distinctio voluptatem earum eum?
      Eveniet provident recusandae nisi aliquam magni, quae pariatur dolorum sed eligendi delectus tempore voluptatem corporis ducimus nulla ullam! Quidem facere explicabo debitis alias veniam! Amet illum unde excepturi quia voluptates!
      Consequuntur accusamus fugiat beatae provident, modi architecto maxime eum, dicta tempore adipisci dolore facilis saepe dolorem. Cum laudantium sapiente tenetur harum numquam ullam voluptas, in consequuntur quis quasi, necessitatibus placeat?
      Ipsa dolor quam id fuga aliquam. Aperiam facilis sapiente incidunt officia voluptate assumenda voluptas ex excepturi sint sunt eveniet accusantium saepe rem, temporibus earum maxime nisi est optio perspiciatis repudiandae.
      Laudantium cumque totam culpa quidem. Sit accusantium rem quibusdam, dolorem est ab quisquam soluta sint recusandae fuga architecto at debitis illum minima quis dicta eum quod aperiam molestiae impedit explicabo.
      Ipsa cumque nisi facere obcaecati veniam accusantium earum, aspernatur sapiente dolor, tempora magnam labore! Reprehenderit maxime veritatis nemo quis reiciendis cupiditate adipisci, sed id quam perferendis vel in, rerum eum?
      Iure aliquam dolore magni doloremque repellat voluptas perferendis tempore explicabo doloribus! Tempora necessitatibus, ab nesciunt amet a sapiente. Repellat modi quae maxime ad facere sint aliquam sunt accusantium ea sequi?
      Tempora, soluta quasi harum ad, alias vero tempore quas omnis voluptatum doloribus non expedita quibusdam animi! Sapiente labore necessitatibus recusandae, unde temporibus voluptas ratione ipsam nobis possimus facere architecto! Ex!
      Odio quasi obcaecati explicabo voluptate unde inventore ex exercitationem earum? Aperiam laudantium fuga maiores, facilis ab error. Incidunt possimus voluptatibus vitae praesentium cumque, porro, ipsam laudantium, accusamus modi natus hic.
      Laudantium molestiae necessitatibus vero facere explicabo. Nemo ipsa rerum illum quisquam similique sapiente, aspernatur excepturi impedit labore officia blanditiis possimus, atque amet necessitatibus perspiciatis? Mollitia labore nobis harum nulla ipsa!</div>
    </div>
  );
}
export default About;
